version: '3.7'
services:
  DTH:
    image: dinesh359/phonepe_dth:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: dinesh359/phonepe_train:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  loan:
    image: dinesh359/phonepe_loan
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: dinesh359/phonepe_recharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
